#!/usr/bin/env python3
"""
Phase 3b — Written mock paper + mark scheme generation.

Consumes blueprint.json and generates an ORIGINAL exam question per slot (with a full
mark scheme) using a strong LLM, emulating the recurring template's style but with new
numbers/context. Validates that per-part marks reconcile to the slot total.

Outputs (per paper) under data/predictions/{code}/{session}_{year}/:
  paper.json            structured questions + schemes
  paper_p{pid}.md       printable paper (LaTeX math)
  markscheme_p{pid}.md  printable mark scheme

Usage: python scripts/predictor/05_generate_paper.py --subject 4PM1
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.env import REPO_ROOT
from lib.config import load_config, PredictorConfig
from lib.llm import chat_json, LLMError

FALLBACK_MODELS = ["anthropic/claude-3.5-haiku", "openai/gpt-4o-mini"]
DISCLAIMER = ("AI-PREDICTED PRACTICE PAPER — generated by GradeMax from historical question "
              "patterns. NOT an official Pearson/Edexcel paper and NOT leaked content.")


def gen_question(cfg: PredictorConfig, paper_name: str, n_q: int, slot: dict,
                 avoid: list[str] | None = None) -> dict:
    prov = cfg.llm["generate"]["provider"]
    model = cfg.llm["generate"]["model"]
    sref = slot.get("style_reference", {})
    sys_msg = (
        f"You are a senior Edexcel International GCSE {cfg.name} ({cfg.code}) examiner and "
        "question author. Write ONE original exam question that matches the given specification "
        "exactly. Render ALL mathematics in LaTeX (inline $...$, display $$...$$) and include "
        "units for Physics. Numbers and context MUST be new (do not copy the style reference). "
        "Ensure the question is solvable and the mark scheme is correct. Return ONLY a JSON object."
    )
    avoid_block = ""
    if avoid:
        bullets = "\n".join(f"- {a}" for a in avoid)
        avoid_block = (
            "\nThis paper ALREADY contains the following questions. Your question MUST test a "
            "clearly DIFFERENT sub-skill / scenario and must NOT resemble any of them:\n"
            f"{bullets}\n")
    user_msg = f"""{paper_name}, Question {slot['slot']} of {n_q}.
Topic: {slot['topic_name']}
Target marks: {slot['marks']}   Difficulty: {slot['difficulty']}
Aim for about {slot.get('est_subparts', 2)} labelled sub-parts (a), (b), (c)...
Command words to use where natural: {', '.join(slot.get('command_words', []))}
Skills to assess: {', '.join(slot.get('skills', []))}
Style reference (emulate the TYPE/STYLE only, not the content): "{sref.get('example_excerpt','')}" ({sref.get('example_marks')} marks)
{avoid_block}
Rules:
- Per-part marks MUST sum to exactly {slot['marks']}.
- If the question has only one task, still give it a single part labelled "(a)".
- If a figure/diagram is essential, describe it in "diagram_note" (a placeholder will be drawn).
- Double-check your own arithmetic before finalising.

Return JSON with EXACTLY these keys:
{{
  "stem": "<shared setup text, markdown+LaTeX, may be empty>",
  "diagram_note": "<describe a figure if essential, else empty string>",
  "parts": [
    {{"label": "(a)", "marks": <int>, "prompt": "<question text>", "mark_scheme": "<working + answer with M/A marks>"}}
  ],
  "total_marks": {slot['marks']},
  "final_answers": "<concise answer key>"
}}"""
    messages = [{"role": "system", "content": sys_msg}, {"role": "user", "content": user_msg}]
    models = [model] + [m for m in FALLBACK_MODELS if m != model]
    last: Exception | None = None
    # Two passes over the model list so a transient parse/HTTP error still recovers.
    for attempt in range(2):
        for m in models:
            try:
                q = chat_json(prov, m, messages, temperature=0.6 + 0.1 * attempt, max_tokens=2200)
                if q.get("parts"):
                    return q
                last = ValueError("no parts in response")
            except Exception as e:  # noqa: BLE001 — incl. JSON parse + LLM errors -> try fallback
                last = e
                continue
    raise last if last else LLMError("generation failed")


def _descriptor(slot: dict, q: dict) -> str:
    """Short summary of a generated question, used to keep later questions distinct."""
    first = (q.get("stem") or "")
    if not first and q.get("parts"):
        first = q["parts"][0].get("prompt", "")
    return f"Q{slot['slot']} [{slot['topic_name']}]: {first[:110]}"


def build_paper(cfg: PredictorConfig, pid: str, bp: dict) -> dict:
    n_q = bp["question_count"]
    questions = []
    used_by_topic: dict[str, list[str]] = {}
    for slot in bp["slots"]:
        avoid = used_by_topic.get(slot["topic"], [])
        q, parts, psum = None, [], -1
        # Retry up to 3 times to land the exact mark total before flagging.
        for attempt in range(3):
            try:
                cand = gen_question(cfg, bp["paper_name"], n_q, slot, avoid=avoid)
            except Exception as e:
                print(f"    ! gen failed Q{slot['slot']} (try {attempt+1}): {str(e)[:90]}")
                continue
            cparts = cand.get("parts", []) or []
            csum = sum(int(p.get("marks", 0)) for p in cparts)
            if q is None or abs(csum - slot["marks"]) < abs(psum - slot["marks"]):
                q, parts, psum = cand, cparts, csum   # keep the closest-marks candidate
            if csum == slot["marks"]:
                break
        if q is None:
            q = {"stem": "", "diagram_note": "", "parts": [
                {"label": "(a)", "marks": slot["marks"], "prompt": "[generation failed — regenerate]",
                 "mark_scheme": ""}], "total_marks": slot["marks"], "final_answers": ""}
            parts, psum = q["parts"], slot["marks"]
        used_by_topic.setdefault(slot["topic"], []).append(_descriptor(slot, q))
        needs_review = psum != slot["marks"]
        questions.append({
            "slot": slot["slot"], "topic": slot["topic"], "topic_name": slot["topic_name"],
            "target_marks": slot["marks"], "actual_marks": psum,
            "confidence_band": slot["confidence_band"], "needs_review": needs_review,
            "stem": q.get("stem", ""), "diagram_note": q.get("diagram_note", ""),
            "parts": parts, "final_answers": q.get("final_answers", ""),
        })
        flag = " ⚠ marks mismatch" if needs_review else ""
        print(f"    Q{slot['slot']:>2} {slot['topic_name'][:28]:<28} {psum}/{slot['marks']}m{flag}")
    return {"paper": pid, "paper_name": bp["paper_name"], "total_marks": bp["total_marks"],
            "question_count": n_q, "questions": questions}


def render_paper_md(cfg: PredictorConfig, paper: dict) -> str:
    L = [f"# {cfg.name} ({cfg.code}) — PREDICTED {paper['paper_name']}",
         f"### {cfg.target['label']}  ·  Total {sum(q['actual_marks'] for q in paper['questions'])} marks",
         f"> ⚠️ {DISCLAIMER}\n", "---\n"]
    for q in paper["questions"]:
        L.append(f"**{q['slot']}.**  " + (q["stem"] or ""))
        if q.get("diagram_note"):
            L.append(f"\n> _[Figure: {q['diagram_note']}]_\n")
        single = len(q["parts"]) == 1
        for p in q["parts"]:
            lbl = (p.get("label") or "").strip()
            prefix = "" if (single and not lbl) else f"**{lbl or '(a)'}** "
            L.append(f"\n{prefix}{p.get('prompt','')}  _({p.get('marks',0)})_")
        L.append(f"\n_(Total for Question {q['slot']} = {q['actual_marks']} marks)_\n")
        L.append("---\n")
    return "\n".join(L)


def render_ms_md(cfg: PredictorConfig, paper: dict) -> str:
    L = [f"# {cfg.name} ({cfg.code}) — Mark Scheme: PREDICTED {paper['paper_name']}",
         f"### {cfg.target['label']}", f"> ⚠️ {DISCLAIMER}\n", "---\n"]
    for q in paper["questions"]:
        L.append(f"### Question {q['slot']} — {q['topic_name']} ({q['actual_marks']} marks)")
        single = len(q["parts"]) == 1
        for p in q["parts"]:
            lbl = (p.get("label") or "").strip()
            head = "" if (single and not lbl) else f"**{lbl or '(a)'}** "
            L.append(f"\n{head}_({p.get('marks',0)} marks)_\n")
            L.append(p.get("mark_scheme", "") or "_(none)_")
        if q.get("final_answers"):
            L.append(f"\n**Answers:** {q['final_answers']}")
        L.append("\n---\n")
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--subject", required=True)
    ap.add_argument("--paper", help="only this paper id (1 or 2)")
    args = ap.parse_args()
    cfg = load_config(args.subject)
    out_dir = REPO_ROOT / "data" / "predictions" / cfg.code / f"{cfg.target['session']}_{cfg.target['year']}"
    bp = json.loads((out_dir / "blueprint.json").read_text(encoding="utf-8"))

    all_papers = {}
    for pid, paper_bp in bp["papers"].items():
        if args.paper and pid != args.paper:
            continue
        print(f"[{cfg.code}] generating {paper_bp['paper_name']} ({paper_bp['question_count']} questions)…")
        paper = build_paper(cfg, pid, paper_bp)
        all_papers[pid] = paper
        (out_dir / f"paper_p{pid}.md").write_text(render_paper_md(cfg, paper), encoding="utf-8")
        (out_dir / f"markscheme_p{pid}.md").write_text(render_ms_md(cfg, paper), encoding="utf-8")
        nr = sum(1 for q in paper["questions"] if q["needs_review"])
        print(f"  -> paper_p{pid}.md + markscheme_p{pid}.md  ({nr} question(s) need review)")

    paper_json = out_dir / "paper.json"
    existing = json.loads(paper_json.read_text(encoding="utf-8")) if paper_json.exists() else {}
    existing.update(all_papers)
    paper_json.write_text(json.dumps({"subject_code": cfg.code, "target": cfg.target, "papers": existing},
                                     ensure_ascii=False, indent=2), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
